version: "3"

services:
  postgres:
    image: postgres:13
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - airflow-network

  airflow:
    container_name: airflow
    build:
      context: .
      dockerfile: dockerfile.docker
      args:
        - AIRFLOW_HOME=${AIRFLOW_HOME}
    secrets:
      - aws
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - AWS_CONFIG_FILE=/run/secrets/aws
      - AWS_S3_BUCKET_NAME=${AWS_S3_BUCKET_NAME}
    volumes:
      - ./dags:${AIRFLOW_HOME}/dags
      - ./airflow.cfg:${AIRFLOW_HOME}/airflow.cfg
    ports:
      - 8080:8080
    networks:
      - airflow-network

  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    platform: linux/amd64
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: ${POSTGRES_DB}
      MB_DB_PORT: 5432
      MB_DB_USER: ${POSTGRES_USER}
      MB_DB_PASS: ${POSTGRES_PASSWORD}
      MB_DB_HOST: postgres
    ports:
      - 3000:3000
    networks:
      - airflow-network
    
  
secrets:
  aws:
    file: ./credentials

networks:
  airflow-network:
